version: '3.8'

services:
  javafx-calculator:
    build:
      context: .
    container_name: javafx_calculator
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI support (JavaFX)
    ports:
      - "8080:8080"  # Map container's port 8080 to host
    tty: true
